
services:
  - type: worker
    name: okfor-btc-bot
    runtime: python
    repo: https://github.com/OleksaKov/okfor_btc_bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
